# Nakładanie na siebie struktur, oraz liczenie RMSD

W tym cwiczeniu napiszemy skrpyt który będzie odpowienikiem użycia komend pymol:<br>
load data/7qvb_A.pdb<br>
load data/af2_pred.pdb<br>
pair_fit n. CA and resid 5-158 and m. 7qvb_A and c. A,n. CA and resid 9-162 and m. af2_pred and c. A 

In [1]:
import numpy as np

<h3> Etap:1/5 Tworzenie parsera </h3><br>

You are restricted to using the numpy library.<br> 
Write a Python function <i>parse_pdb_file</i> that parses a given PDB file to extract specific information from lines starting with ATOM and HETATM. <br>
The required output <i>atom_data</i> should be a list of dictionaries, where each dictionary contains the following fields extracted from the specified positions in the text line:<br>

- X: Coordinate from positions 31–38
- Y: Coordinate from positions 39–46
- Z: Coordinate from positions 47–54
- Atom Name: Text from positions 13–16
- Residue Sequence Number: Number from positions 23–26
- Chain Identifier: Single character at position 22

Keep in mind that positions are 1-based, not 0-based indexes.<br>
You can read more about PDB format here:<br>
<a href="https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html">https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html</a>

```
def parse_pdb_file(file_path):
    atom_data = []
    
    #for iteration through all "ATOM" and "HETATM" lines
    
        atom_info = {
        'X': x,
        'Y': y,
        'Z': z,
        'AtomName': atom_name,
        'ResidueSeqNumber': residue_seq_number,
        'ChainID': chain_id
        }
        #appending atom_info to atom_data list
    
    return atom_data

In [2]:
def parse_pdb_file(file_path):
    atom_data = []
    
    #for iteration through all "ATOM" and "HETATM" lines
    file = open(file_path, "r")
    for line in file:
        if(line[0:4] == "ATOM" or line[0:6] == "HETATM"):
            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])
            atom_name = line[12:16].strip()
            residue_seq_number = float(line[22:26])
            chain_id = line[21]
            
            atom_info = {
            'X': x,
            'Y': y,
            'Z': z,
            'AtomName': atom_name,
            'ResidueSeqNumber': residue_seq_number,
            'ChainID': chain_id
            }
            #appending atom_info to atom_data list
            atom_data.append(atom_info)
    
    return atom_data

In [3]:
#wykorzystanie funkcji
reference_pdb_path = './data/7qvb_A.pdb'
model_pdb_path = './data/af2_pred.pdb'

reference_data = parse_pdb_file(reference_pdb_path)
model_data = parse_pdb_file(model_pdb_path)
print(reference_data)

[{'X': 29.66, 'Y': -3.18, 'Z': -11.216, 'AtomName': 'N', 'ResidueSeqNumber': 5.0, 'ChainID': 'A'}, {'X': 31.055, 'Y': -3.288, 'Z': -11.677, 'AtomName': 'CA', 'ResidueSeqNumber': 5.0, 'ChainID': 'A'}, {'X': 31.967, 'Y': -2.237, 'Z': -11.02, 'AtomName': 'C', 'ResidueSeqNumber': 5.0, 'ChainID': 'A'}, {'X': 32.239, 'Y': -1.222, 'Z': -11.642, 'AtomName': 'O', 'ResidueSeqNumber': 5.0, 'ChainID': 'A'}, {'X': 30.94, 'Y': -3.09, 'Z': -13.199, 'AtomName': 'CB', 'ResidueSeqNumber': 5.0, 'ChainID': 'A'}, {'X': 29.778, 'Y': -2.135, 'Z': -13.347, 'AtomName': 'CG', 'ResidueSeqNumber': 5.0, 'ChainID': 'A'}, {'X': 28.826, 'Y': -2.524, 'Z': -12.234, 'AtomName': 'CD', 'ResidueSeqNumber': 5.0, 'ChainID': 'A'}, {'X': 29.614, 'Y': -2.626, 'Z': -10.432, 'AtomName': 'H', 'ResidueSeqNumber': 5.0, 'ChainID': 'A'}, {'X': 31.393, 'Y': -4.199, 'Z': -11.488, 'AtomName': 'HA', 'ResidueSeqNumber': 5.0, 'ChainID': 'A'}, {'X': 31.762, 'Y': -2.705, 'Z': -13.571, 'AtomName': 'HB2', 'ResidueSeqNumber': 5.0, 'ChainID': 'A'

<h3>Etap:2/5 tworzenie filtru danych</h3>

Write a function that takes atom_data as input and filters it based on two criteria:

- The ResidueSeqNumber must fall within a specified range provided as a list (e.g., [5, 6, 7, ..., 210]).
- The AtomName must be equal to "CA".

The function should return the filtered data as filtered_atom_data.

Below is the partially written function for you to complete:<br>
<br>
```
def filter_atom_data(atom_data, residue_numbers, atom_name):
    filtered_atom_data = []
    
    # Add filtering logic here
    
    return filtered_atom_data 

In [4]:
def filter_atom_data(atom_data, residue_numbers, atom_name):
    filtered_atom_data = []
    for atom in atom_data:
        if (atom['ResidueSeqNumber'] in residue_numbers and atom['AtomName'] == atom_name):
            filtered_atom_data.append(atom)
    
    
    return filtered_atom_data  

In [5]:
#wykorzystanie funkcji
atom_name_to_filter = 'CA'

residue_numbers_to_filter = list(range(5,159))
filtered_reference_data = filter_atom_data(reference_data, residue_numbers_to_filter, atom_name_to_filter)

residue_numbers_to_filter = list(range(9,163))
filtered_model_data = filter_atom_data(model_data, residue_numbers_to_filter, atom_name_to_filter)
print(filtered_model_data)

[{'X': -10.754, 'Y': 11.062, 'Z': 21.086, 'AtomName': 'CA', 'ResidueSeqNumber': 9.0, 'ChainID': 'A'}, {'X': -9.278, 'Y': 9.626, 'Z': 17.887, 'AtomName': 'CA', 'ResidueSeqNumber': 10.0, 'ChainID': 'A'}, {'X': -5.741, 'Y': 11.027, 'Z': 17.486, 'AtomName': 'CA', 'ResidueSeqNumber': 11.0, 'ChainID': 'A'}, {'X': -3.368, 'Y': 10.988, 'Z': 14.521, 'AtomName': 'CA', 'ResidueSeqNumber': 12.0, 'ChainID': 'A'}, {'X': 0.097, 'Y': 10.554, 'Z': 16.059, 'AtomName': 'CA', 'ResidueSeqNumber': 13.0, 'ChainID': 'A'}, {'X': 2.985, 'Y': 11.753, 'Z': 13.767, 'AtomName': 'CA', 'ResidueSeqNumber': 14.0, 'ChainID': 'A'}, {'X': 6.205, 'Y': 11.318, 'Z': 15.753, 'AtomName': 'CA', 'ResidueSeqNumber': 15.0, 'ChainID': 'A'}, {'X': 5.789, 'Y': 13.707, 'Z': 18.734, 'AtomName': 'CA', 'ResidueSeqNumber': 16.0, 'ChainID': 'A'}, {'X': 2.821, 'Y': 15.474, 'Z': 17.021, 'AtomName': 'CA', 'ResidueSeqNumber': 17.0, 'ChainID': 'A'}, {'X': -0.72, 'Y': 14.615, 'Z': 18.184, 'AtomName': 'CA', 'ResidueSeqNumber': 18.0, 'ChainID': 'A

<h3> Etap: 3/5 ekstrakcja położeń atomów</h3>

Create a function that extracts the X, Y, and Z coordinates from atom_data and returns them as a NumPy array with a shape of (n_atoms, 3), where n_atoms is the number of atoms.

```
def extract_xyz_positions(atom_data):
    # Extract the X, Y, and Z coordinates from atom_data
    # and store them in a NumPy array.
    
    
    return xyz_positions

In [6]:
def extract_xyz_positions(atom_data):
    #code
    
    xyz_positions=[]
    for atom in atom_data:
        xyz_positions.append([atom['X'], atom['Y'], atom['Z']])
    return np.array(xyz_positions)

In [7]:
#uzyj kodu
filtered_reference_data_xyz = extract_xyz_positions(filtered_reference_data)
filtered_model_data_xyz = extract_xyz_positions(filtered_model_data)
print(filtered_model_data_xyz)

[[-1.0754e+01  1.1062e+01  2.1086e+01]
 [-9.2780e+00  9.6260e+00  1.7887e+01]
 [-5.7410e+00  1.1027e+01  1.7486e+01]
 [-3.3680e+00  1.0988e+01  1.4521e+01]
 [ 9.7000e-02  1.0554e+01  1.6059e+01]
 [ 2.9850e+00  1.1753e+01  1.3767e+01]
 [ 6.2050e+00  1.1318e+01  1.5753e+01]
 [ 5.7890e+00  1.3707e+01  1.8734e+01]
 [ 2.8210e+00  1.5474e+01  1.7021e+01]
 [-7.2000e-01  1.4615e+01  1.8184e+01]
 [-3.6700e+00  1.5832e+01  1.6085e+01]
 [-7.2810e+00  1.5130e+01  1.7198e+01]
 [-9.2280e+00  1.3484e+01  1.4333e+01]
 [-1.2948e+01  1.3131e+01  1.3629e+01]
 [-1.4609e+01  9.7140e+00  1.3145e+01]
 [-1.4243e+01  1.0279e+01  9.3290e+00]
 [-1.0501e+01  1.1161e+01  9.6450e+00]
 [-1.0478e+01  1.5000e+01  9.3640e+00]
 [-7.9680e+00  1.6863e+01  1.1562e+01]
 [-9.0440e+00  1.9385e+01  1.4226e+01]
 [-8.3370e+00  2.2750e+01  1.2542e+01]
 [-7.3480e+00  2.4827e+01  1.5677e+01]
 [-4.6690e+00  2.2170e+01  1.6479e+01]
 [-3.6480e+00  2.2065e+01  1.2778e+01]
 [-3.3310e+00  2.5921e+01  1.2821e+01]
 [-9.5900e-01  2.5660e+01

<h3> Etap 4/5 Nałożenie na siebie struktur</h3><br>
Google: Finding optimal rotation and translation between corresponding 3d points python<br>
<a href="https://nghiaho.com/?page_id=671">https://nghiaho.com/?page_id=671</a><br>
<a href="https://jasonblog.github.io/note/math/finding_optimal_rotation_and_translation_between_c.html">https://jasonblog.github.io/note/math/finding_optimal_rotation_and_translation_between_c.html</a>




Given the input arrays filtered_reference_data_xyz and filtered_model_data_xyz, calculate the rotation matrix R and the translation vector t to align the coordinates. Use only the numpy library for the implementation.

```
def align_coordinates(xyz_moving_A, xyz_fixed_B):
    # Code to compute the rotation matrix (R) and translation vector (t)
    # to align the coordinates of xyz_moving_A to xyz_fixed_B
    
    ###
    
    return R, t

In [8]:
from math import sqrt

def align_coordinates(xyz_moving_A, xyz_fixed_B):
    # Code to compute the rotation matrix (R) and translation vector (t)
    # to align the coordinates of xyz_moving_A to xyz_fixed_B
    
    #code
    A=xyz_moving_A
    B=xyz_fixed_B
    assert len(A) == len(B)

    N = A.shape[0]; # total points

    centroid_A = np.mean(A, axis=0)
    centroid_B = np.mean(B, axis=0)

    # centre the points
    AA = A - np.tile(centroid_A, (N, 1))
    BB = B - np.tile(centroid_B, (N, 1))

    # dot is matrix multiplication for array
    H = np.transpose(AA) @ BB

    U, S, Vt = np.linalg.svd(H)

    R = Vt.T @ U.T

    # special reflection case
    if np.linalg.det(R) < 0:
        print("Reflection detected")
        Vt[2,:] @= -1
        R = Vt.T @ U.T

    t = -R@centroid_A.T + centroid_B.T
    return R, t
    
    

In [9]:
#użeyj k
R,t=align_coordinates( filtered_model_data_xyz,filtered_reference_data_xyz)
filtered_model_data_xyz_fitted=filtered_model_data_xyz@R.T+t
print(filtered_model_data_xyz_fitted)

[[ 31.26989241  -3.29587264 -12.55952423]
 [ 33.20358061  -2.0855641   -9.51481141]
 [ 36.67902426  -0.9926136  -10.68131114]
 [ 39.82860087  -0.19255073  -8.71562002]
 [ 41.45798      2.68171016 -10.62448697]
 [ 45.25624427   3.05544383  -9.94263608]
 [ 46.49058017   5.8853351  -12.17197484]
 [ 45.89788251   4.58514685 -15.73918075]
 [ 45.35225335   0.99676144 -14.43861896]
 [ 41.76853603  -0.313465   -14.17516518]
 [ 41.15892136  -3.57837431 -12.28886534]
 [ 37.62160941  -5.06071472 -12.04191377]
 [ 36.76115871  -5.76728301  -8.37193613]
 [ 34.17287255  -8.01796729  -6.73065004]
 [ 31.55168777  -6.65773641  -4.29175106]
 [ 33.90582052  -7.77315466  -1.42313848]
 [ 36.9458946   -5.99360762  -2.99524088]
 [ 38.91773868  -8.88190651  -4.60364736]
 [ 40.61542637  -8.1436977   -7.94654689]
 [ 39.7476857  -10.03437731 -11.15396216]
 [ 42.66866138 -12.48382721 -11.51036953]
 [ 42.89549359 -12.63239422 -15.38938358]
 [ 43.2381333   -8.79036077 -15.42503432]
 [ 45.70493783  -8.97110722 -12.48

<h3> 5/5 Obliczanie RMSD</h3>

Create a function to calculate the Root Mean Square Deviation (RMSD) between two sets of coordinates, xyz_A and xyz_B.

```
def calculate_rmsd(xyz_A, xyz_B):
    
    #code
    
    return rmsd

In [10]:
def calculate_rmsd(xyz_A, xyz_B):
    diff = xyz_A - xyz_B
    return np.sqrt((diff * diff).sum() / xyz_A.shape[0])

In [11]:
print(f"RMSD pre fit: {calculate_rmsd(filtered_reference_data_xyz, filtered_model_data_xyz)}") 
print(f"RMSD post fit: {calculate_rmsd(filtered_reference_data_xyz, filtered_model_data_xyz_fitted)}") 

RMSD pre fit: 61.05354976357858
RMSD post fit: 1.3577310013044088


# Obliczanie GDT_TS przy pomocy biblioteki pymol

GDT_TS - GlobalDistanceTest_TotalScore<br>
GDT_TS = (GDT_P1 + GDT_P2 + GDT_P4 + GDT_P8)/4,<br>
where GDT_Pn denotes percent of residues under distance cutoff <= nÅ <br>

In [12]:
#conda install conda-forge::pymol-open-source
#https://pymolwiki.org/index.php/Main_Page
import pymol

In [13]:
#zaczynanie od poczatku
pymol.cmd.delete('all')

#otwieranie struktur
pymol.cmd.load('./data/7qvb_A.pdb', object="reference")
#pymol.cmd.load('./data/af2_pred.pdb', object="model_")
#pymol.cmd.load('./data/I-TASSER_exclude.pdb', object="model_")
pymol.cmd.load('./data/I-TASSER_100ident.pdb', object="model_")

#dopasowanie af2_pred do 7qvb_A
rmsd=pymol.cmd.pair_fit("n. CA and resid 9-162+173-226 and m. model_ and c. A",
                  "n. CA and resid 5-158+169-222 and m. reference and c. A and not alt B")




#stwórz pętle po resids z model_resids oraz reference_resids, a następnie oblicz dystans za pomoca get_distance
#pomiedzy atomami CA 
model_resids=list(range(9,163))+list(range(173,227))
reference_resids=list(range(5,159))+list(range(169,223))
n_1=0
n_2=0
n_4=0
n_8=0
n_total=len(reference_resids)
for resid_model, resid_ref in zip(model_resids, reference_resids):
        atom1=f"n. CA and resid {resid_model} and m. model_ and c. A"
        atom2=f"n. CA and resid {resid_ref} and m. reference and c. A and not alt B"
        distance=pymol.cmd.get_distance(atom1, atom2)
        if distance < 1:
            n_1+=1
        if distance < 2:
            n_2+=1  
        if distance < 4:
            n_4+=1 
        if distance < 8:
            n_8+=1 

        #sprawdz czy odpowiadajace sobie atomy (atom1 oraz atom2) spełniaja pierwsza kategorie -> dystans mniejszy od 1
        # jesli tak podnies o 1 licznik n_1
        #itd

    #Oblicz GDT_P1, GDT_P2,GDT_P4,GDT_P8
GDT_P1=n_1/n_total*100
GDT_P2=n_2/n_total*100
GDT_P4=n_4/n_total*100
GDT_P8=n_8/n_total*100

GDT_TS = (GDT_P1 + GDT_P2 + GDT_P4 + GDT_P8)/4
    #...
    #Oblicz GDT_TS

print(GDT_P1,GDT_P2,GDT_P4,GDT_P8)
print("GDT_TS wynosi: %.2f%%" % GDT_TS)

98.07692307692307 99.51923076923077 100.0 100.0
GDT_TS wynosi: 99.40%


Zakomentuj 6. linijke kodu i odkomentuj poszczegolne struktury z I-TASSERA i sprawdz wyniki

<h2>TM-SCORE</h2>

Proszę wejść na stronę:<br>
<a href="https://zhanggroup.org/TM-score/">https://zhanggroup.org/TM-score/</a>

Jako model spróbować użyć:
1. data/af2_pred_truncated_aligned.pdb
2. data/I-TASSER_exclude_truncated_aligned.pdb
3. I-TASSER_100ident_truncated_aligned.pdb

Jako strukturę eksperymentalną:
data/7qvb_A.pdb

<h2>Verify 3D</h2>

Wejdź na stronę Verify3D:<br>
<a href="https://www.doe-mbi.ucla.edu/verify3d/">https://www.doe-mbi.ucla.edu/verify3d/</a>    <br><br>
A następnie:<br>
-uruchom program dla naszej referncji-struktury eksperymentalnej<br>
data/7qvb_A.pdb<br>
-uruchom program dla modelu z alphafold2<br>
data/af2_pred.pdb<br>
-uruchom program dla modelu z serwera I-TASSER<br>
data/I-TASSER_exclude.pdb<br>

Dla wyników z af2 nacisnij na przycisk "Save to data file" a nastepnie dla tego zestawu danych wygeneruj podobny<br>
wykres do tego z strony verify3D

In [16]:
from matplotlib import pyplot as plt